SET SEARCH_PATH = CINES;

INSERT INTO PELICULA (TITULO_ORIGINAL, TITULO_ESPAÑOL,TITULO_DISTRIB, FECHA_ESTRENO, RESUMEN, DURACION,CALIFICACION, IDIOMA_ORIG, URL,GENERO,ANIO_PRODUC) VALUES
-- aca van los datos (, , , , ), y el ultimo (, , , ,);

INSERT INTO PERSONA (DNI, NOMBRE, NACIONALIDAD) VALUES

INSERT INTO CINE (NOMBRE_CINE, TELEFONO, DIRECCION) VALUES

INSERT INTO SALA (CANT_BUTACA, NOMBRE_CINE) VALUES

INSERT INTO FUNCION (ID_PELICULA, ID_SALA, FECHA,HORA_COMIENZO, HORA_FINALIZACION) VALUES

INSERT INTO PAISES_PELICULA (ID_PELICULA, NOMBRE_PAIS) VALUES

INSERT INTO DIRIGE (ID_PELICULA, DNI) VALUES

INSERT INTO PROTAGONIZO (ID_PELICULA, DNI) VALUES

INSERT INTO REPARTO (ID_PELICULA, DNI) VALUES 