DROP SCHEMA IF EXISTS cines CASCADE;
CREATE SCHEMA cines;

DROP TABLE IF EXISTS cines.PERSONA;

-- Establecer el esquema por defecto
SET SEARCH_PATH = cines;

-- Crear dominios
CREATE DOMAIN ENTEROPOSITIVO AS INT DEFAULT 0 CHECK (VALUE > 0);

CREATE DOMAIN CALIFICACION_TIPO AS VARCHAR(20)
CHECK (VALUE IN ('Apta todo público', '+13 años', '+15 años', '+18 años'));
-- Tablas

CREATE TABLE cines.PELICULA (
	ID_PELICULA SERIAL NOT NULL,
	TITULO_ORIGINAL VARCHAR(255) DEFAULT NULL,
	TITULO_ESPANOL VARCHAR(255) DEFAULT NULL,
	TITULO_DISTRIB VARCHAR(255) DEFAULT NULL,
	FECHA_ESTRENO DATE NOT NULL, 
	RESUMEN TEXT NOT NULL,
	DURACION ENTEROPOSITIVO NOT NULL,
	CALIFICACION CALIFICACION_TIPO NOT NULL, 
	IDIOMA_ORIG VARCHAR(50) DEFAULT NULL, 
	URL VARCHAR(255) DEFAULT NULL,
	GENERO VARCHAR(50) DEFAULT NULL,
	ANIO_PRODUC ENTEROPOSITIVO NOT NULL,
	PRIMARY KEY (ID_PELICULA)
);

CREATE TABLE cines.PERSONA (
	DNI ENTEROPOSITIVO NOT NULL, 
	NOMBRE VARCHAR(255),
	NACIONALIDAD VARCHAR(50), 
	CANT_PELICULA ENTEROPOSITIVO,
	PRIMARY KEY (DNI)
);


